Music-Site-Capstone/MyTopBillboard

pom.xml
also commented out the spring security dependencies for now.
=> added correct dependencies for pom.xml file

.gitignore, src/main/resources/templates/homepage.html, src/main/resources/templates/landing_page.html, src/main/resources/templates/partials.html, src/main/resources/templates/profile.html, src/main/resources/templates/registration.html
=> view skeletons added

src/main/java/com/mytopbillboard/repositories/ArtistRepository.java, src/main/java/com/mytopbillboard/repositories/GenreRepository.java, src/main/java/com/mytopbillboard/repositories/PlaylistRepository.java, src/main/java/com/mytopbillboard/repositories/RatingRepository.java, src/main/java/com/mytopbillboard/repositories/SongRepository.java, src/main/java/com/mytopbillboard/repositories/UserRepository.java
Added The Repository Directory, Added Repositories for Artist, Genre, Playlist, Rating, Song, and User.
=> Joshua sprouse

src/main/java/com/mytopbillboard/models/Song.java
still needs the annotations and more.
=> created the song model

src/main/java/com/mytopbillboard/repositories/ArtistRepository.java, src/main/java/com/mytopbillboard/repositories/GenreRepository.java, src/main/java/com/mytopbillboard/repositories/PlaylistRepository.java, src/main/java/com/mytopbillboard/repositories/RatingRepository.java, src/main/java/com/mytopbillboard/repositories/SongRepository.java
Fixed some typos, Added methods into Repos, Imported Classes into all Repos
=> Imported Classes into Repositories, Added Methods into all Repos

pom.xml, src/main/resources/templates/js/spotify_api.js
Cleaned duplicate pom.xml dependancies125
=> pom.xml cleanup

src/main/resources/static/js/spotify_api.js, src/main/resources/templates/partials/partials.html, src/main/resources/templates/registration.html
=> Added stlysheet to partials

src/main/resources/templates/siteViews/homepage.html
=> new homepage layout

song.sql, src/main/java/com/mytopbillboard/controllers/PlaylistController.java, src/main/java/com/mytopbillboard/controllers/UserController.java, src/main/java/com/mytopbillboard/repositories/RatingRepository.java, src/main/java/com/mytopbillboard/repositories/SongRepository.java, src/main/resources/static/js/modal.js, src/main/resources/templates/siteViews/profile.html
Addition of Profile Ratings and creation of PlayList
=> addition of ratings

src/main/java/com/mytopbillboard/controllers/HomeController.java, src/main/resources/templates/siteViews/homepage.html
=> fixed navigation links

system.properties
=> System properties

src/main/java/com/mytopbillboard/controllers/AuthenticationController.java, src/main/java/com/mytopbillboard/controllers/HomeController.java, src/main/java/com/mytopbillboard/controllers/UserController.java, src/main/resources/static/js/spotify_api.js, src/main/resources/templates/login.html, src/main/resources/templates/siteViews/homepage.html
fixed white label parsing error
=> Richard kim

src/main/java/com/mytopbillboard/controllers/HomeController.java, src/main/resources/static/js/registration.js
=> Aaron morris

src/main/resources/static/js/profile.js, src/main/resources/static/js/spotify_api.js, src/main/resources/templates/siteViews/profile.html
fixed append issue and now songs are going to correct playlist
=> fixed append issue and now songs go to correct playlist ID

src/main/java/com/mytopbillboard/controllers/PlaylistController.java, src/main/resources/templates/login.html, src/main/resources/templates/partials/partials.html, src/main/resources/templates/registration.html, src/main/resources/templates/siteViews/homepage.html, src/main/resources/templates/siteViews/landing_page.html, src/main/resources/templates/siteViews/profile.html
=> Fixed Delete Playlist

src/main/resources/templates/siteViews/landing_page.html
changed carousel to one direction with card layout
=> landing page edits

src/main/resources/static/css/landing.css, src/main/resources/templates/siteViews/landing_page.html
=> css styling moved to landing.css

src/main/resources/static/css/landing.css, src/main/resources/templates/siteViews/landing_page.html
=> added vibeCheck icon

src/main/resources/static/css/landing.css, src/main/resources/templates/siteViews/landing_page.html
fixed mobile view functionality and is now consistent with desktop
=> landing mobile view

src/main/resources/static/css/landing.css, src/main/resources/templates/siteViews/landing_page.html
version 2 with some titles and css edits
=> landing page v2

src/main/resources/static/css/landing.css, src/main/resources/templates/siteViews/landing_page.html
created icon animation on landing page
=> icon animation created

src/main/resources/static/css/landing.css
=> landing page v3

src/main/resources/templates/siteViews/about.html
=> updated about me

src/main/resources/static/css/profile.css, src/main/resources/static/js/profile.js, src/main/resources/templates/siteViews/profile.html
Trophies Displays on Profile Page.
=> addition of profileTrophies

src/main/resources/static/js/profile.js
Bug fix for displaying trophy on Profile.
=> profile trophy fix

src/main/resources/static/css/modal.css, src/main/resources/static/css/profile.css, src/main/resources/static/js/profile.js
=> Scrollbar Adjustment

src/main/resources/static/css/site.css, src/main/resources/static/js/profile.js, src/main/resources/static/js/spotify_api.js, src/main/resources/templates/siteViews/profile.html
=> addition of TrashCans
